version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: spm-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: street-performers-map
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - spm-network

  redis:
    image: redis:7.2-alpine
    container_name: spm-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - spm-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  redis_data:
    driver: local

networks:
  spm-network:
    driver: bridge
