[build]
builder = "NIXPACKS"
buildCommand = "pnpm install --frozen-lockfile && pnpm --filter @spm/shared-types build && pnpm --filter @spm/backend build && pnpm --filter @spm/frontend build && cp -r apps/frontend/dist apps/backend/dist/"
watchPatterns = ["apps/backend/**", "apps/frontend/**", "packages/**"]

[deploy]
startCommand = "cd apps/backend && pnpm --filter @spm/backend start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = { default = "3001" }